from typing import List, Optional
from pydantic import BaseModel, Field

# 1. Define a strict nested model for the data
class PayloadData(BaseModel):
    underperforming_lines_count: Optional[int] = Field(default=None)
    target_line_id: Optional[str] = Field(default=None)
    low_stock_items: Optional[List[str]] = Field(default=None)
    bottleneck_station: Optional[str] = Field(default=None)

# 2. Update your main response model
class AgentResponse(BaseModel):
    status: str = Field(..., description="The outcome of the request (e.g., SUCCESS, CLARIFICATION_REQUIRED, ERROR).")
    responding_agent: str = Field(..., description="The name of the agent that finalized the response sequence.")
    message: str = Field(..., description="The natural language answer generated by the agent team.")
    # FIX: Use the rigid nested model instead of Dict[str, Any]
    data_payload: Optional[PayloadData] = Field(
        default=None, 
        description="Raw tool metrics extracted from the factory analysis."
    )

class UserMessage(BaseModel):
    text: str = Field(
        ..., 
        description="The natural language instruction or query from the shop floor.",
        json_schema_extra={"example": "Which assembly lines are running below 80% throughput right now?"}
    )
    session_id: Optional[str] = Field(
        default="default-session", 
        description="Used to maintain conversation or state history across execution steps."
    )

